### ISSUE TITLE
Preciso de Ajuda

### ISSUE THREAD

**Issue by dayvidallan** [rg3915/vendas#38]
Bom dia Professor,

Estou tendo um problema na hora de inicializar o projeto de vendas, sempre reporta esse erro:
 File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\shlex.py", line 137, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'

a linha 137 tem o seguinte código:
 while True:
            if self.punctuation_chars and self._pushback_chars:
                nextchar = self._pushback_chars.pop()
            else:
                **nextchar = self.instream.read(1)**
            if nextchar == '\n':
                self.lineno += 1
            if self.debug >= 3:
                print("shlex: in state %r I see character: %r" % (self.state,
                                                                  nextchar))
            if self.state is None:
                self.token = ''        # past end of file

instalei a versão 3.7 do python e o django 2

**Comment by rg3915** [comment]
@dayvidallan atualizei o projeto. Tenta novamente por favor.

**Comment by dayvidallan** [comment]
Boa noite Professo,

Muito Obrigado, mas estou lutando com esse erro:


(.venv) C:\Users\easyg\vendas>manage.py makemigrations core
Traceback (most recent call last):
  File "C:\Users\easyg\vendas\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\django\core\management\__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\easyg\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\easyg\vendas\vendas\settings.py", line 13, in <module>
    SECRET_KEY = config('SECRET_KEY')
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\decouple.py", line 85, in __call__
    return self.get(*args, **kwargs)
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\decouple.py", line 70, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.

(.venv) C:\Users\easyg\vendas>manage.py makemigrations core
Traceback (most recent call last):
  File "C:\Users\easyg\vendas\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\django\core\management\__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\easyg\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\easyg\vendas\vendas\settings.py", line 17, in <module>
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=[], cast=Csv())
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\decouple.py", line 85, in __call__
    return self.get(*args, **kwargs)
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\decouple.py", line 79, in get
    return cast(value)
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\decouple.py", line 233, in __call__
    return self.post_process(transform(s) for s in splitter)
  File "C:\Users\easyg\vendas\vendas\.venv\lib\site-packages\decouple.py", line 233, in <genexpr>
    return self.post_process(transform(s) for s in splitter)
  File "C:\Users\easyg\AppData\Local\Programs\Python\Python37-32\lib\shlex.py", line 295, in __next__
    token = self.get_token()
  File "C:\Users\easyg\AppData\Local\Programs\Python\Python37-32\lib\shlex.py", line 105, in get_token
    raw = self.read_token()
  File "C:\Users\easyg\AppData\Local\Programs\Python\Python37-32\lib\shlex.py", line 136, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'

________________________________
De: Regis da Silva <notifications@github.com>
Enviado: sexta-feira, 11 de outubro de 2019 18:41
Para: rg3915/vendas <vendas@noreply.github.com>
Cc: dayvidallan <dayvidallan@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [rg3915/vendas] Preciso de Ajuda (#38)


@dayvidallan<https://github.com/dayvidallan> atualizei o projeto. Tenta novamente por favor.

**Comment by rg3915** [comment]
@dayvidallan vc precisa rodar o comando que está no README.
`cp contrib/env-sample .env`

**Comment by dayvidallan** [comment]
Muitíssimo obrigado professor,

Eu estou aprendendo a programar e uso o windows, e não consigo rodar esse comando.
________________________________
De: Regis da Silva <notifications@github.com>
Enviado: sábado, 12 de outubro de 2019 01:08
Para: rg3915/vendas <vendas@noreply.github.com>
Cc: dayvidallan <dayvidallan@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [rg3915/vendas] Preciso de Ajuda (#38)


@dayvidallan<https://github.com/dayvidallan> vc precisa rodar o comando que está no README.
cp contrib/env-sample .env

**Comment by dayvidallan** [comment]
consegui Professor,

Muito Obrigado, me ajudou muito.
________________________________
De: Regis da Silva <notifications@github.com>
Enviado: sábado, 12 de outubro de 2019 01:08
Para: rg3915/vendas <vendas@noreply.github.com>
Cc: dayvidallan <dayvidallan@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [rg3915/vendas] Preciso de Ajuda (#38)


@dayvidallan<https://github.com/dayvidallan> vc precisa rodar o comando que está no README.
cp contrib/env-sample .env
